### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by bryanbocao** [caiyuanhao1998/MST#32]
```
MST/simulation/train_code# python3 train.py --template mst_s --outf ./exp/mst_s/ --method mst_s
training sences: 502
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    train_set = LoadTraining(opt.data_path)
  File "/share/home/brcao/Repos/MST/simulation/train_code/utils.py", line 39, in LoadTraining
    scene_num = int(scene_list[i].split('.')[0][5:])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by bryanbocao** [comment]
```
MST/simulation/train_code/utils.py
```
```
 31 def LoadTraining(path):
 32     imgs = []
 33     scene_list = os.listdir(path)
 34     scene_list.sort()
 35     print('training sences:', len(scene_list))
 36     for i in range(len(scene_list)):
 37     # for i in range(5):
 38         scene_path = path + scene_list[i]
 39         print('\n utils.py - scene_path: ', scene_path)
```
```
 utils.py - scene_path:  ../../datasets//cave_1024_28/.DS_Store
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    train_set = LoadTraining(opt.data_path)
  File "/share/home/brcao/Repos/MST/simulation/train_code/utils.py", line 40, in LoadTraining
    scene_num = int(scene_list[i].split('.')[0][5:])
ValueError: invalid literal for int() with base 10: ''
```

Solved by removing the ```.DS_Store``` file in the unzipped folder from Mac.
